In [ ]:
Inventory & Sales Management System

In [ ]:
Why this title: This Python project automates inventory tracking.
And alsosales analysis to improve business decision-making in retail systems.

In [ ]:
Objective:The objective of this project is to automate inventory tracking and sales analysis using Python to improve efficiency, accuracy, and business insights.

In [ ]:
Problem Statement:To manage inventory and sales using Python to reduce manual work, avoid errors, and analyze sales and profit easily.

In [1]:
import pandas as pd  # by import libraries

In [2]:
df = pd.read_csv("Sales.csv")
df.head()

,Category,SubCategory,Value1,Value2,Score,Rating,Sales,Quantity,Profit,Region
0,C,Z,293,5.512274,47,4,5899.259471,13,2921.476851,East
1,D,Y,37,59.643866,38,5,3620.779541,46,4243.000398,East
2,A,Y,117,68.172333,92,1,47968.533347,35,4722.363430,West
3,C,Y,53,3.132242,41,4,42510.014061,6,308.904145,North
4,C,Y,349,51.889957,25,5,18390.354333,18,4596.231938,West

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Category     100 non-null    object
 1   SubCategory  100 non-null    object
 2   Value1       100 non-null    int64
 3   Value2       100 non-null    float64
 4   Score        100 non-null    int64
 5   Rating       100 non-null    int64
 6   Sales        100 non-null    float64
 7   Quantity     100 non-null    int64
 8   Profit       100 non-null    float64
 9   Region       100 non-null    object
dtypes: float64(3), int64(4), object(3)
memory usage: 7.9+ KB

In [4]:
total_sales = df["Sales"].sum()
total_sales

np.float64(2615223.783363186)

In [5]:
total_profit = df["Profit"].sum()
total_profit

np.float64(178720.53573385332)

In [6]:
sales_by_region = df.groupby("Region")["Sales"].sum()
sales_by_region

Region
East     634201.267746
North    554367.567620
South    773619.928169
West     653035.019828
Name: Sales, dtype: float64

In [7]:
profit_by_category = df.groupby("Category")["Profit"].sum()
profit_by_category

Category
A    37310.348056
B    41004.969093
C    51651.482933
D    48753.735651
Name: Profit, dtype: float64

In [8]:
best_selling = df.sort_values(by="Quantity", ascending=False).head(5)
best_selling

,Category,SubCategory,Value1,Value2,Score,Rating,Sales,Quantity,Profit,Region
25,B,X,465,63.797183,65,4,34713.470499,49,557.589603,East
18,D,Y,130,81.914664,15,2,48738.162218,49,3024.811096,West
58,C,Z,11,97.244239,39,5,12637.817093,49,4423.637607,South
33,B,X,181,9.779373,62,3,8183.636263,48,634.835451,South
76,D,Z,256,3.020931,0,1,15430.203395,48,2241.432094,East

In [9]:
low_stock = df[df["Quantity"] > 40]
low_stock

,Category,SubCategory,Value1,Value2,Score,Rating,Sales,Quantity,Profit,Region
1,D,Y,37,59.643866,38,5,3620.779541,46,4243.000398,East
6,A,Y,455,64.985003,49,2,34161.725317,47,920.344136,East
11,C,X,240,15.032061,6,5,30519.605369,45,2983.704699,East
17,D,X,455,66.442430,7,4,46615.526179,47,263.549450,South
18,D,Y,130,81.914664,15,2,48738.162218,49,3024.811096,West
25,B,X,465,63.797183,65,4,34713.470499,49,557.589603,East
29,D,X,174,89.775650,85,3,21878.482277,41,473.557664,North
33,B,X,181,9.779373,62,3,8183.636263,48,634.835451,South
52,C,Y,110,66.209109,5,5,29002.178235,46,1529.025018,West
54,C,Z,449,10.717597,93,2,38592.547802,45,3611.090160,East
58,C,Z,11,97.244239,39,5,12637.817093,49,4423.637607,South
71,B,Z,181,18.927691,89,5,13396.518231,44,158.691725,East
76,D,Z,256,3.020931,0,1,15430.203395,48,2241.432094,East
77,D,Z,333,92.846547,57,4,49795.737376,47,-21.938416,East

In [10]:
avg_rating = df["Rating"].mean()
avg_rating

np.float64(3.0)

In [13]:
df.to_csv("Final_Sales_Report.csv", index=False)
print("Report exported successfully")

Report exported successfully